name: RealEstateDeals
favicon: null
layout_spectrum: 0.99001
typography_spectrum: 0.49565
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#40773d'
    - '#1753ab'
    - '#78ac3e'
    - '#9db6dc'
    - '#000000'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
